apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1 # Certifique-se de definir a quantidade de réplicas
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: dlricarte/projeto-database:1.0
        args:
          - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-dados
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-dados
        persistentVolumeClaim:
          claimName: mysql-dados

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1 # Certifique-se de definir a quantidade de réplicas
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: dlricarte/projeto-backend:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
