apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.50.100 # Altere para um IP do intervalo configurado no MetalLB


---

apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: LoadBalancer
  loadBalancerIP: 192.168.50.99 # Altere para outro IP do intervalo configurado no MetalLB


